GET  http://localhost:3001/api/notes

##############


GET http://localhost:3001/api/fakeendpoint

DELETE http://localhost:3001/api/notes/1

##############

POST http://localhost:3001/api/notes/
Content-Type: application/json

{
  "content": "VS CODE REST is pretty good",
  "important": false
}