GET http://localhost:3003/api/blogs

###################

POST http://localhost:3003/api/blogs
Content-Type: application/json
//Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlN1cGVyIFVzZXIiLCJpZCI6IjYyZWRiY2MyMTljMmMxNzMxNmY1MTY0YSIsImlhdCI6MTY1OTkyMTA0OCwiZXhwIjoxNjU5OTI0NjQ4fQ.M1cR823hTtEGptsOL8qn1yuBCAs270eomiB8TDW4OSk

{
  "title": "Blog From authorized user",
  "author": "Author McAuthorized",
  "url": "token.com",
  "likes": 1
} 